language: python
python:
    - "2.7"
    - "3.2"
install:
    - pip install nose coverage --use-mirrors
    - pip install . --use-mirrors
script: nosetests --with-doctest --with-coverage --cover-package=peinard
